---
title: "FigureYa21 TCGA2table"
params:
  author: "Guangchuang Yu"
output: latex_document
---

**Author(s)**: `r params$author`  
**Date**: `r Sys.Date()`  

# Academic Citation
If you use this code in your work or research, we kindly request that you cite our publication:

Xiaofan Lu, et al. (2025). FigureYa: A Standardized Visualization Framework for Enhancing Biomedical Data Interpretation and Research Efficiency. iMetaMed. https://doi.org/10.1002/imm3.70005



```{r,message=FALSE}
source("install_dependencies.R")
library(dplyr)
x = read.csv("easy_input.csv")

x1 = x %>% filter(vital_status == "Alive") 
x2 = x %>% filter(vital_status == "Dead" & person_neoplasm_cancer_status == "WITH TUMOR") 
x3 = x %>% filter(vital_status == "Dead" & person_neoplasm_cancer_status == "TUMOR FREE")

xx = x %>% filter(vital_status != "" & person_neoplasm_cancer_status != "")

s1 = x1 %>% group_by(gender) %>% summarise(alive=n())
s1
s2 = x2 %>% group_by(gender) %>% summarise(tumor=n())
s3 = x3 %>% group_by(gender) %>% summarise(tumor_free=n())

## sex

sex = full_join(s1, s2, by='gender') %>% full_join(s3, by='gender') %>% as.data.frame
sex

rn = sex[,1]
sex = sex[,-1]

sex.p = chisq.test(sex)$p.value
print(sex.p)

sex$total = rowSums(sex)
cs = colSums(sex)

sex <- rbind(paste0(sex[1,], " (", sprintf("%1.1f\\%%", sex[1,]/cs*100), ")"),
    paste0(sex[2,], " (", sprintf("%1.1f\\%%", sex[2,]/cs*100), ")"))

rownames(sex) = rn
colnames(sex) = paste0(c("Alive", "Dead with tumor", "Dead tumor free", "Total"), 
                "\n(n=", cs, ")")
print(sex)

## age

age_stats <- function(x) {
   res <- x %>% summarise(age = round(mean(age_at_initial_pathologic_diagnosis,na.rm = T), 1), 
                sd=round(sd(age_at_initial_pathologic_diagnosis,na.rm = T), 1),
                median=round(median(age_at_initial_pathologic_diagnosis,na.rm = T), 1),
                min=round(min(age_at_initial_pathologic_diagnosis,na.rm = T), 1),
                max=round(max(age_at_initial_pathologic_diagnosis,na.rm = T), 1)
                )
   c("Mean (SD)" = with(res, paste0(age, " (", sd, ")")),
       "Median [MIN, MAX]" = with(res, paste0(median, " [", min, ",", max, "]"))#,
   )             
}

a1 = age_stats(x1)
a2 = age_stats(x2)
a3 = age_stats(x3)
aa = age_stats(xx)

age = cbind(a1, a2) %>% cbind(a3) %>% cbind(aa)

colnames(age) = colnames(sex)
print(age)

## Stage

stage_stats <- function(x) {
    x %>% filter(stage_event_pathologic_stage != "") %>% 
        group_by(stage_event_pathologic_stage) %>% summarise(stage = n())
}

sg1 = stage_stats(x1)
sg2 = stage_stats(x2)
sg3 = stage_stats(x3)
sgx = stage_stats(xx)
sg = full_join(sg1, sg2, by="stage_event_pathologic_stage") %>% 
    full_join(sg3, by="stage_event_pathologic_stage") %>% 
    full_join(sgx, by="stage_event_pathologic_stage") %>% 
    as.data.frame

rownames(sg) = sg[,1]
sg = sg[,-1]
colnames(sg) = colnames(sex)

print(sg)

# chisq test
sgx <- sg[, -4]
sgx <- sgx[!apply(sgx, 1, anyNA),]
sg.p = chisq.test(sgx)$p.value

sgv2 = lapply(1:nrow(sg), function(i) ifelse(is.na(sg[i,]), "", 
    paste0(sg[i,], " (", sprintf("%1.1f\\%%", sg[i,]/cs * 100), ")"))) %>% 
    do.call(rbind, .)

rownames(sgv2) = rownames(sg)
colnames(sgv2) = colnames(sg)
print(sgv2)

## combine

res = rbind(sex, age) %>% rbind(sgv2) %>% as.data.frame
print(res)


#install.packages("kableExtra")
require(kableExtra)

if (knitr:::is_html_output()) {
    cn = sub("\n", "<br>", colnames(res))
} else if (knitr:::is_latex_output()) {
    usepackage_latex('makecell')
    usepackage_latex('booktabs')
    cn = linebreak(colnames(res), align="c")
}   

res %>%
    kable(booktabs = T, escape = F, caption = "Example Table",
        col.names = cn) %>%
    kable_styling(c("striped", "scale_down")) %>%
    group_rows("Gender*", 1, 2) %>% 
    group_rows("Age", 3, 4) %>% 
    group_rows("Stage", 5, 13) %>% 
    footnote(general = "significant",
             #general = paste("P-value =", sg.p), 
             general_title = "*: ", 
             footnote_as_chunk = T, title_format = "italic")
```

\newpage

```{r eval=T, echo=F}
res[["P Value"]] = c("", paste0(round(sex.p, 3), footnote_marker_symbol(1)), ## sex
                 rep("", 2), ## age
                 rep("", nrow(sg)-1), round(sg.p, 3) ## stage
                 )
cn <- c(cn, "P Value") 
res %>%
    kable(booktabs = T, escape = F, caption = "Example Table",
        col.names = cn) %>%
    kable_styling(c("striped", "scale_down")) %>%
    group_rows("Gender", 1, 2) %>% 
    group_rows("Age", 3, 4) %>% 
    group_rows("Stage", 5, 13) %>% 
    footnote(general = "significant", 
             #general = paste("P-value =", sg.p), 
            general_title = "*", 
            footnote_as_chunk = T, title_format = "italic")
```

\newpage

```{r}
sessionInfo()
```