name: Generate searchable index for main

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-searchable-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main branch to root
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install bs4
        run: pip install beautifulsoup4

      - name: Build searchable docs
        run: python .github/scripts/generate_searchable_index_png.py

      - name: Commit and push index/search files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html chapters.json texts/
          git commit -m "Auto-generate searchable docs [skip ci]" || echo "Nothing to commit"
          git push origin HEAD:main
