name: Process Rmd Files

on:
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  process-rmd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"  # 使用 Python 版本

    - name: Run Python script to process Rmd files
      run: |
        mkdir -p .github/docs
        python .github/scripts/extract_functions_from_rmd.py

    - name: Move output to docs folder
      run: |
        mv rmd_functions_packages.csv .github/docs/

    - name: Commit and push results
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .github/docs/rmd_functions_packages.csv
        git commit -m "Processed Rmd files and updated documentation"
        git push origin main
