name: Sync master folders to main (no overwrite)

on:
  workflow_dispatch:

jobs:
  check-and-copy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master
          path: master_src

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main_dst

      - name: Check for folder name conflicts
        run: |
          cd master_src
          # 只查找一级目录
          for d in */ ; do
            if [ -d "../main_dst/$d" ]; then
              echo "Error: main 分支已存在同名文件夹: $d"
              exit 1
            fi
          done

      - name: Copy folders from master to main workspace
        run: |
          cd master_src
          for d in */ ; do
            cp -a "$d" ../main_dst/
          done

      - name: Commit and push to main
        run: |
          cd main_dst
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync folders from master (no overwrite)" || echo "Nothing to commit"
          git push origin HEAD:main
